# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source /usr/share/oh-my-zsh/oh-my-zsh.sh
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# fzf (below oh-my-zsh)
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

plugins=(git)

# flutter
export CHROME_EXECUTABLE=/usr/bin/brave
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
export PATH=~/flutter/bin:$PATH
export PATH=~/Android/Sdk/platform-tools:$PATH
# cargo
export PATH=$PATH:~/.cargo/bin
export EDITOR='nvim'

eval "$(zoxide init zsh)"

alias l="exa -la"
alias e='nvim'
alias lg='lazygit'
alias ra='ranger'
alias n="n -ex"
alias t="ydcv"

# ^g to open lazygit (below oh-my-zsh)
bindkey -s '^g' 'lazygit\n'

ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
